# Generated by Django 4.0.4 on 2022-05-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0002_alter_game_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(related_name='Attendees', to='levelupapi.gamer'),
        ),
    ]
