# Generated by Django 4.0.4 on 2022-05-07 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0003_event_attendees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(related_name='Gamers', to='levelupapi.gamer'),
        ),
    ]
